// DO NOT edit this file to insert a new component. Edit configure.js instead.
import {hot} from 'react-hot-loader';
import React from 'react';
import styled, {ThemeProvider} from 'styled-components'
import {App as AppStructure, AppBody} from './structure/App'
import {Body as BodyWrapperMarkup} from './structure/Body'
import {
  HEADER_HEIGHT,
  FOOTER_HEIGHT,
  LEFT_SIDEBAR_WIDTH,
  LeftSidebar,
  Content,
  Header,
  Footer,
  themes
} from './configure'

const BodyWrapper = styled(BodyWrapperMarkup)`
  width: 100%;
  height: 100%; // this is the height of < Body> below
  display: flex;
`


const BodyMarkup = ({left, center, right, ...rest}) => {
  return (
    <AppBody
      {...rest}
    >
      <BodyWrapper>
        {left && left}
        {center && center}
        {right && right}
      </BodyWrapper>
    </AppBody>
  )
}

const Body = styled(BodyMarkup)`
  height: calc(100vh - ${HEADER_HEIGHT + FOOTER_HEIGHT}px);
  --height: calc(100vh - ${HEADER_HEIGHT + FOOTER_HEIGHT}px);
`


function App() {
  return (
    <AppStructure>
      <ThemeProvider
        theme={themes.default}
      >
        <Header
          height={HEADER_HEIGHT}
        />
        <Body
          left={<LeftSidebar
            width={LEFT_SIDEBAR_WIDTH}
          />}
          center={<Content/>}
        />
        <Footer
          height={FOOTER_HEIGHT}
        />
      </ThemeProvider>
    </AppStructure>
  )
}

export default hot(module)(App)
